# SonarCloud Configuration

# Must be unique in a given SonarQube instance
sonar.projectKey=amenkhelil_tt-recruit-platform
sonar.organization=amen

# --- optional properties ---

# encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Source paths
sonar.sources=backend/src,frontend/src,AI-service/app

# Exclusions
sonar.exclusions=**/node_modules/**,**/venv/**,**/dist/**,**/build/**,**/*.test.js,**/*.spec.js,**/*.test.jsx
